apiVersion: v1
kind: ReplicationController
metadata:
  name: myvertex-rc
spec:
   replicas: 3
   selector: 
     app: myvertexapp
     version: 2.6.1
   template:                                     
     metadata:
       labels:
          app: myvertexapp
          version: 2.6.1
     spec:
        containers:
        - name: myonlineapp-container
          image: nbktechnosys/myjavaimage11nov22:1
          ports:
          - containerPort: 8080 